version: '3'
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    expose:
      - 5432
    ports:
      - 8000:8000
    depends_on:
      - routes_database

  routes_database:
    image: postgres:13-alpine
    container_name: routes_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:${POSTGRES_PORT}

volumes:
  postgres_data:
